### ISSUE TITLE
Banner blocks render as file blocks

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-elemental-bannerblock#1]
Currently if you add a banner block with no theming the block is rendered as if it's a file block:

![image](https://user-images.githubusercontent.com/3260989/41450081-7aee3214-70b9-11e8-8d1f-597b40edcb5d.png)

**Comment by robbieaverill** [comment]
Note: we only added default styles for this module to the cwp/starter-theme, not the simple theme. This might be expected behaviour.

**Comment by ScopeyNZ** [comment]
I cheated by checking that it wasn't expected before raising it :P - It also meant the fix was ready immediately
