### ISSUE TITLE
Should BlockLinkField be pulled out into its own module?

### ISSUE THREAD

**Issue by altwohill** [silverstripe/silverstripe-elemental-bannerblock#10]
I'm just making a new Elemental block module and using this one for inspiration. To me the link feature should be a shared dependency as it has uses outside of just banners.

Thoughts?

**Comment by ScopeyNZ** [comment]
Thanks @altwohill. Good idea! Unfortunately this field is quite tightly coupled to this particular use case - but it'd definitely be awesome to recreate it against a more appropriate repository like admin. If this was to be done the dialog would probably have to be significantly refactored.

You're welcome to make a PR against admin if you want to have a go - but it's something that looks easier on the surface I think 😂

**Comment by altwohill** [comment]
My particular use case is a block that holds details of speakers at a conference-  so it has an image, a name, a role, a description, and a link to more info. 

The blocklinkfield to me shouldn't be restricted to block UI either... it reminds me of https://github.com/sheadawson/silverstripe-linkable however I see that is no longer maintained. 

I'll see if I get a bit of time to see how it would fit into admin.

**Comment by ScopeyNZ** [comment]
Sorry, I meant the implementation is coupled to the use case here. I think the link modal you get is the same link modal from TinyMCE, so then you need a TinyMCE field on the page for this field to work. A bit of a hack, so the link modal will probably have to be reimplemented for this to have its own module (or for it to live in admin). 

It'll be pretty interesting to create a new modal though. Admin already has a component that can be used to select pages from the site tree: `TreeDropdownField`

**Comment by robbieaverill** [comment]
Yeah I agree with both of you - the field could be standalone, but it currently is tightly coupled to TinyMCE. We did this at the time in order to re-use the "insert link" modal, but the modal itself in core is built in a way that is tightly coupled to TinyMCE, so we added more coupling =D

In order to do this we'd either need to do as @ScopeyNZ said and recreate the modal as a standalone component in this module, or work on refactoring it out in silverstripe-admin first, then update the code here

**Comment by robbieaverill** [comment]
>the field could be standalone, but it currently is tightly coupled to TinyMCE

This is no longer the case. We've missed the window for this in the 2.0 release though, so it'd need to be done in `master` for the next major release (3.0)

**Comment by chillu** [comment]
https://github.com/gorriecoe/silverstripe-linkfield is a pretty common replacement now (3k downloads on packagist: https://packagist.org/packages/gorriecoe/silverstripe-linkfield).

**Comment by ScopeyNZ** [comment]
> [gorriecoe/silverstripe-linkfield](https://github.com/gorriecoe/silverstripe-linkfield) is a pretty common replacement now (3k downloads on packagist: [packagist.org/packages/gorriecoe/silverstripe-linkfield](https://packagist.org/packages/gorriecoe/silverstripe-linkfield)).

There's been some discussion around this. `linkfield` is a great option too but it won't work in this context - we need something that will work with `FormBuilderModal` - ie. it has to be React.

While that does prevent us from using `linkfield` now - we could just work on upgrading that to React and using it instead.

Side note; I'm dropping the effort back to medium as the hard part is done now 😅

**Comment by chillu** [comment]
I've created a wider discussion on how to proceed with this in terms of a reuseable link moudle: https://forum.silverstripe.org/t/new-links-module/1642

**Comment by GuySartorelli** [comment]
There is already work to make a separate link module. Closing this issue.
