### ISSUE TITLE
Unable to edit in-line if block was empty when created

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-elemental-bannerblock#11]
If a banner block is created from GridFieldDetailForm without any content, when the user attempts to expand the block for in-line editing, the block does not expand. Expected behaviour is the block should expand and allow the user to add content.

Steps to recreate:
1. Add Banner block to page
2. Create Banner block with no content
3. Attempt to expand the block for editing in edit mode
4. Identify that block does not expand

**Comment by ScopeyNZ** [comment]
Issue moved to [silverstripe/silverstripe-elemental-fileblock #7](https://github.com/silverstripe/silverstripe-elemental-fileblock/issues/7) via [**ZenHub**](https://www.zenhub.com/)
