### ISSUE TITLE
Turn into SilverStripe commercially supported module

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-elemental-bannerblock#16]
Since https://github.com/silverstripe/silverstripe-elemental-blocks is deprecated, we should add this to the supported modules.

- [x] Add to https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list site
- [x] Add to [supported-modules](https://github.com/silverstripe/supported-modules) repo
- [x] Add ![image](https://user-images.githubusercontent.com/14869519/47690503-28d14600-dc53-11e8-829c-c410a271f960.png) badge

**Comment by robbieaverill** [comment]
All done
