### ISSUE TITLE
Casing of "Call to action link" is incorrect

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-elemental-bannerblock#19]
### Affected Version

2.x

### Description

It currently reads "Call To Action Link" but it should be "Call to action link"

### Steps to reproduce

- View a banner block
- Note the field title
- Click the field to add a link
- Note the title of the modal

cc @sachajudd

**Comment by robbieaverill** [comment]
Fix at #20 

This field label is automatically scaffolded by silverstripe/framework, so it's bound to be an issue in other places.

`CallToActionLink` -> `Call To Action Link`
