### ISSUE TITLE
"Clear link" button did not work

### ISSUE THREAD

**Issue by MichelleZZZZ** [silverstripe/silverstripe-elemental-bannerblock#26]
**Issue description:**
The "Clear link" button on the "Call to action" field is not working.
After removed the link, and save the changes and publish the block. But the link field still loading the previous link after open the block accordion.

![clear-link](https://user-images.githubusercontent.com/50159313/57003060-0c20c580-6c18-11e9-825a-41b97919a14f.PNG)

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/29

**Comment by robbieaverill** [comment]
@MichelleZZZZ can you please provide the module versions you're using?

**Comment by MichelleZZZZ** [comment]
Thanks for replying.
In my composer.lock file the version is 2.0.0

"name": "silverstripe/elemental-bannerblock",
 "version": "2.0.0",
"source": {
       "type": "git",
        "url": "https://github.com/silverstripe/silverstripe-elemental-bannerblock.git",
       "reference": "cde2dfa65eba63a8e33fc1344f9f4615e8d93746"
 },

**Comment by robbieaverill** [comment]
Thanks @MichelleZZZZ, can you also provide dnadesign/silverstripe-elemental and silverstripe/admin versions?

**Comment by MichelleZZZZ** [comment]
dnadesign/silverstripe-elemental version is:
"require": {
        "dnadesign/silverstripe-elemental": "^4@dev",
       "silverstripe/assets": "^1.3",
       "silverstripe/cms": "^4.3",
       "silverstripe/vendor-plugin": "^1.0"
},

silverstripe/admin versions
"name": "silverstripe/admin",
       "version": "1.3.0",
       source": {
       "type": "git",
       "url": "https://github.com/silverstripe/silverstripe-admin.git",
       "reference": "4f68e4b759c104b2690050af034a41d370d2e6e4"
 },

**Comment by robbieaverill** [comment]
Can you please paste the output of `composer show | grep silverstripe-elemental`? Your excerpt above doesn't contain a specific version for it =)

**Comment by MichelleZZZZ** [comment]
Sure, please have a look.

dnadesign/silverstripe-elemental          4.0.3              Elemental pagetype and collection of Elements
silverstripe/elemental-bannerblock        2.0.0             A banner block for the silverstripe-elemental module
silverstripe/elemental-fileblock          2.0.0              A file block for the silverstripe-elemental module

**Comment by maxime-rainville** [comment]
The issue seems to be somewhat worst on my end:
* The first time I try to set a value in the link field, it doesn't stick at all. The second time works fine ;
* Clear doesn't work, as previously stated ;
* Update an existing link doesn't seem to work either. The call to action change doesn't seem to stick, but the selected page seems to ... at least until you try editing the link again.

https://youtu.be/pPw6MhTpyJM

I'll try adding the link field to a plain data object and see if it behaves better when it's not access via an elemental area.

**Comment by ScopeyNZ** [comment]
Closed in #26
