### ISSUE TITLE
Entwine wrapper for BlockLinkField appears to be broken

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-elemental-bannerblock#27]
Affected version: **2.0.1**

The BlockLinkField works as expected in the ElementalEditor context, but if inline editing is disabled for the Banner Block, this field doesn't render at all. Entwine appears to be matching the element as expected, but the call to `createReactComponent()` seems to silently fail (in my testing, the body of the createReactComponent method was not run at all).

**Comment by muskie9** [comment]
Attempted this as a workaround for #30 and found this to be the case.

**Comment by thats4shaw** [comment]
I've had a crack at fixing this and there's a PR at https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/41.

Seems to be some context or load ordering issue when calling `this.createReactComponent()` within `onmatch`.  From all the other examples I could find it seemed that just handling the logic within `onmatch` seemed to be the default when mixing react components and entwine e.g. https://github.com/silverstripe/silverstripe-tagfield/blob/2/client/src/legacy/entwine/TagField.js.  Seemed the simplest way to fix it so i've gone with that.

**Comment by Cheddam** [comment]
#41 is now merged, so I'm closing this out. The fix will make its way into the next release.
