### ISSUE TITLE
Add behavioural tests

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-elemental-bannerblock#9]
Similar to the ones, added to `silverstripe-elemental` (see https://github.com/creative-commoners/silverstripe-versioned-admin/commit/0d3208b15c52ecccbf09a94d2f688fafe9128d1e), the banner block needs Behat tests as well. 

Note, dependening on the state of silverstripe/silverstripe-behat-extension#180
and dnadesign/silverstripe-elemental#320 these tests may need to add banner blocks via the UI instead of through a fixture and rather than using breadcrumb navigation, we may need to use absolute links to the elemental editor.

**Comment by raissanorth** [comment]
Made a start with https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/12 - there is still a lot of room for improvement though.

**Comment by robbieaverill** [comment]
Done in #12
